### ISSUE TITLE
Important for Xbox Apps!

### ISSUE THREAD

**Issue by LunayderKater** [builtbybel/Winpilot#8]
I used debloos today and used its app removal feuture wich also removes the XboxIdentityProvider App.

If that app is removed you cant sign in into xbox apps like (Minecraft Bedrock or Forza Horizon.)
**There should be a warning there.**

**Comment by Rov3r** [comment]
Didn't read this ahead of time. Now experiencing this issue myself.

**Comment by LunayderKater** [comment]
> 

You can Reinstall it from the Microsoft Store. If you cant find IT directly search it in Google it will Open the Store App .

Link to App: https://apps.microsoft.com/store/detail/xbox-identity-provider/9WZDNCRD1HKW?hl=en-us&gl=us&rtc=1

**Comment by glebinski** [comment]
You can also reinstall using winget itself.

`winget install 9WZDNCRD1HKW` should fix the problem in the meantime.

**Comment by Dreichi** [comment]
Even with installong windows identity provider it's still not working, any idea ?

**Comment by 0x14307** [comment]
What's the error?

**Comment by Dreichi** [comment]
No error just can't login on xbox app even with reinstall of identity provider, had to do reinstall windows

**Comment by Belim** [comment]
With [Winpilot](https://github.com/builtbybel/Winpilot/releases), this shouldn't happen. Proceed with caution and simply refrain from removing the provider.
